version: '3.8'
services:
  studytracker.backend:
    image: studytracker.backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=Server=postgres;Port=5432;User Id=vacheranev;Password=vacheranev;Database=StudyTrackerProd;SearchPath=study_tracker_schema;Include Error Detail=true
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: vacheranev
      POSTGRES_PASSWORD: vacheranev
      POSTGRES_DB: StudyTrackerProd
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: