# This is a generated file. Not intended for manual editing.
services:
  studytracker.backend:
    build:
      context: "C:\\Users\\vovac\\RiderProjects\\StudyTracker.Backend"
      dockerfile: "StudyTracker.Host/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/StudyTracker.Host.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "studytracker.backend:dev"
    ports: []
    volumes:
    - "C:\\Users\\vovac\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\vovac\\RiderProjects\\StudyTracker.Backend\\StudyTracker.Host:/app:rw"
    - "C:\\Users\\vovac\\RiderProjects\\StudyTracker.Backend:/src:rw"
    working_dir: "/app"
